const buildings = [
  "Det odontologiske fakultet",
  "Eilert Sundts hus A",
  "Eilert Sundts hus B",
  "Farmasibygningen",
  "Forskningsparken",
  "Forskningsveien 2B",
  "Frederik Holsts hus",
  "Fysikkbygningen",
  "Geologibygningen",
  "Georg Morgenstiernes hus",
  "GSH - Georg Sverdrups hus",
  "Gydas vei 8",
  "Harald Schjelderups hus",
  "Harriet Holters hus",
  "Helga Engs hus",
  "HELSAM-rom",
  "Henrik Wergelands hus",
  "Historisk museum",
  "IfI sine kollokvierom",
  "Inven2 sine rom",
  "ISF sine rom",
  "Kabelgaten 32-40, Økern",
  "Kada testrom",
  "KHM sine møterom",
  "Kjemibygningen",
  "KLINMED-rom",
  "KNH - Kristen Nygaards hus",
  "KO - Kristian Ottosens hus",
  "Kollokvierom i Fysikkbygningen",
  "Kollokvierom i Georg Sverdrups hus",
  "Kollokvierom i Ole-Johan Dahls hus",
];

export { buildings };
